### ISSUE TITLE
consider not re-inventing the wheel

### ISSUE THREAD

**Issue by idc77** [kyoto-framework/i18n#1]
You're probably having fun developing every aspect of the framework but consider there are already mature libraries where the authors have put considerable research and work into them.
For instance 
https://github.com/nicksnyder/go-i18n

which also has its own external file (toml json) translation workflow.

Or https://github.com/go-playground/universal-translator
which I haven't used.

Translation/i18n is only simple on the surface.
Pluralization rules exist for each language, there's a database of them (cldr).

Feel free to close the issue after you read it. Just trying to provide constructive feedback.

**Comment by yuriizinets** [comment]
Thank you for your note and links!
Just a reminder, you are able to use any solution you want in pair with main library.
I'm not sticking people with a specific solutions.

Also, we had several reasons to create this one:
- Most of solutions are not providing any template functions
- Almost every solution we found have really overcomplicated usage
- There are no functions to take translated value from a struct or map

Just check one more time, f.e. go-i18n, how much things you need to do for a simple thing - take a needed string from a file, accoring to provided language. That's what we needed for our specific project. In most cases you have a long process of setup, and a pretty complex usage.

Also, this package is not for a public use yet. No documentation, examples, etc. It's marked as public just to avoid complications with go packaging and CI. I'll create README with a note.

**Comment by gedw99** [comment]
I like how simple this is . I have used the other two and yes pluralisation is a big area . Datetime, currency also where you need to do conversion from UTC time to the users local time to be shown in the gio.

The thing I noticed on the many solutions to the data time , etc edge cases is that they were not easy to integrate into golang templates. 

It would I feel be useful for this repo to describe what things it needs so that contributors can add them.

the workflow of extracting text , producingvtransaktion templatrs and then updating the many translation files ( with hints of what’s changed or new or deleted in the translation template ) could be done easily also . I just don’t know how @yuriizinets envisages this to work exactly or even if it’s in scope / roadmap.

basing it working off golang templates though seems like a be reusable approach which I like
